version: "3.9"
services:
  web:
    container_name: python-flask
    build: .
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db